config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/apresentacao/:name/:number', to: 'apresentation#home', as:'home'
  get '/comida', to: 'food#now', as: 'food_now'
  get 'calculadora/:num1/:num2', to: 'calculator#home', as:'calculator_home'
  get 'calculadora/soma/:num1/:num2', to:'calculator#sum', as: 'calculator_sum'
  get 'calculadora/subtracao/:num1/:num2', to:'calculator#minus', as: 'calculator_minus'
  get 'calculadora/multiplicacao/:num1/:num2', to:'calculator#multiply', as: 'calculator_multiply'
  get 'calculadora/divisao/:num1/:num2', to:'calculator#division', as: 'calculator_division'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/apresentation_controller.rb
class ApresentationController < ApplicationController
    
    # before_action :ola,only: [:home], expect[:home]  
    def home
        @name = params[:name]
        @number = params[:number].to_i
        # render :lucas #renderiza o html lucas, sem ele vai para o home.html
        # redirect_to Something_path  parecido o link to so q n precisa recarregar o html
    end

    def ola
        @age=20
    end
    

end

app/controllers/calculator_controller.rb
class CalculatorController < ApplicationController

    def home#menu da calculadora
        @num1 = params[:num1]
        @num2 = params[:num2]
        @result = @num1+@num2
    end
    
    def sum#funcao de somar
        @num1 = params[:num1].to_f
        @num2 = params[:num2].to_f
        @result = @num1+@num2
    end

    def minus#funcao de subtrair
        @num1 = params[:num1].to_f
        @num2 = params[:num2].to_f
        @result = @num1-@num2
    end

    def multiply#funcao de multiplicar
        @num1 = params[:num1].to_f
        @num2 = params[:num2].to_f
        @result = @num1*@num2
    end

    def division#funcao de divisao
        @num1 = params[:num1].to_f
        @num2 = params[:num2].to_f
        @result = @num1/@num2
    end
end

app/controllers/food_controller.rb
class FoodController < ApplicationController
    def now
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apresentation/home.html.erb
<% @number.times do%>
<h1 class='red'>Bom Dia <%= @name  %></h1>
<%
=begin%>
 Tbm tem o <%= exibi retorno da funcao 5*5  %> 
<%
=end%>
<% end %>
<%= link_to "Venha Comer", food_now_path, class:'red' %>

app/views/apresentation/lucas.html.erb
<h2>Eu sou Lucas</h2>

app/views/calculator/division.html.erb
<h1>Divisão</h1>

<h1>Ola, você digitou os valores:</h1>
<h2>* <%= @num1  %></h2>
<h2>* <%= @num2  %></h2>
<h2>A divisão é <%= @num1%> / <%= @num2 %> = <%= @result %></h2>

<%
=begin%>
  Links para as outras funções da Classe Matematica
<%
=end%>
<%= link_to "Voltar para o menu?", calculator_home_path %>
<%= link_to "Você deseja subtrair?", calculator_minus_path %>
<%= link_to "Você deseja multiplicar?", calculator_multiply_path %>
<%= link_to "Você deseja dividir?", calculator_division_path %>

app/views/calculator/home.html.erb
<h1>Teste</h1>

<h1>Ola, você digitou os valores:</h1>
<h2>* <%= @num1  %></h2>
<h2>* <%= @num2 %></h2>

<%
=begin%>
  Links para as outras funções da Classe Matematica
<%
=end%>
<%= link_to "Você deseja somar?", calculator_sum_path %>
<%= link_to "Você deseja subtrair?", calculator_minus_path %>
<%= link_to "Você deseja multiplicar?", calculator_multiply_path %>
<%= link_to "Você deseja dividir?", calculator_division_path %>

app/views/calculator/minus.html.erb
<h1>Subtração</h1>

<h1>Ola, você digitou os valores:</h1>
<h2>* <%= @num1  %></h2>
<h2>* <%= @num2  %></h2>
<h2>A subtração é <%= @num1%> - <%= @num2 %> = <%= @result %></h2>

<%
=begin%>
  Links para as outras funções da Classe Matematica
<%
=end%>
<%= link_to "Voltar para o menu?", calculator_home_path %>
<%= link_to "Você deseja subtrair?", calculator_minus_path %>
<%= link_to "Você deseja multiplicar?", calculator_multiply_path %>
<%= link_to "Você deseja dividir?", calculator_division_path %>

app/views/calculator/multiply.html.erb
<h1>Multiplicação</h1>

<h1>Ola, você digitou os valores:</h1>
<h2>* <%= @num1  %></h2>
<h2>* <%= @num2  %></h2>
<h2>A multiplicação é <%= @num1%> x <%= @num2 %> = <%= @result %></h2>

<%
=begin%>
  Links para as outras funções da Classe Matematica
<%
=end%>
<%= link_to "Voltar para o menu?", calculator_home_path %>
<%= link_to "Você deseja subtrair?", calculator_minus_path %>
<%= link_to "Você deseja multiplicar?", calculator_multiply_path %>
<%= link_to "Você deseja dividir?", calculator_division_path %>

app/views/calculator/sum.html.erb
<h1>Soma</h1>

<h1>Ola, você digitou os valores:</h1>
<h2>* <%= @num1  %></h2>
<h2>* <%= @num2  %></h2>
<h2>A soma é <%= @num1%> + <%= @num2 %> = <%= @result %></h2>

<%
=begin%>
  Links para as outras funções da Classe Matematica
<%
=end%>
<%= link_to "Voltar para o menu?", calculator_home_path %>
<%= link_to "Você deseja subtrair?", calculator_minus_path %>
<%= link_to "Você deseja multiplicar?", calculator_multiply_path %>
<%= link_to "Você deseja dividir?", calculator_division_path %>

app/views/food/now.html.erb
<h1>Eu estou com fome</h1>
<%= link_to  "apresentacao", home_path(name:'Lucas', number:6) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aula1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%
=begin%>
  Executa o bloco de codigo q a funcao recebeu => yeld
<%
=end%>
  </body>
</html>